// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7KRxj8LusUzj1FZgJ9gvAxfYjrUOE2ZI',
    appId: '1:435082287533:web:336a898713958e3b4a2924',
    messagingSenderId: '435082287533',
    projectId: 'arniture-e325a',
    authDomain: 'arniture-e325a.firebaseapp.com',
    storageBucket: 'arniture-e325a.appspot.com',
    measurementId: 'G-NN7V9FGCPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbfECkdYIdSk5tODo9z_D4tb1iaExpFRo',
    appId: '1:435082287533:android:e687f9ab247a01c54a2924',
    messagingSenderId: '435082287533',
    projectId: 'arniture-e325a',
    storageBucket: 'arniture-e325a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAubhLyrXiluGKcSDLrq9Pk7B_Teo3vMU4',
    appId: '1:435082287533:ios:cf43482f3ef82fb84a2924',
    messagingSenderId: '435082287533',
    projectId: 'arniture-e325a',
    storageBucket: 'arniture-e325a.appspot.com',
    iosClientId: '435082287533-eqhoam8dno6tg63o3l4dd5grqrt84kru.apps.googleusercontent.com',
    iosBundleId: 'com.example.arniture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAubhLyrXiluGKcSDLrq9Pk7B_Teo3vMU4',
    appId: '1:435082287533:ios:cf43482f3ef82fb84a2924',
    messagingSenderId: '435082287533',
    projectId: 'arniture-e325a',
    storageBucket: 'arniture-e325a.appspot.com',
    iosClientId: '435082287533-eqhoam8dno6tg63o3l4dd5grqrt84kru.apps.googleusercontent.com',
    iosBundleId: 'com.example.arniture',
  );
}
